### ISSUE TITLE
Check why the preview deployments are failing

### ISSUE THREAD

**Issue by joergmis** [Startup-Nights/website#52]
Since vercel provides the possibility for preview deployments, it would be really cool if we get this to work with tina. At the moment it looks like the URL (?) is misconfigured.

```
[17:41:08.108] {
[17:41:08.108]   "heading": "Error when checking client information",
[17:41:08.108]   "items": [
[17:41:08.108]     {
[17:41:08.108]       "emoji": "❌",
[17:41:08.108]       "heading": "You provided",
[17:41:08.108]       "subItems": [
[17:41:08.108]         {
[17:41:08.108]           "key": "clientId",
[17:41:08.108]           "value": "xxxxxxxx"
[17:41:08.108]         },
[17:41:08.108]         {
[17:41:08.109]           "key": "token",
[17:41:08.109]           "value": "xxxxxxxx"
[17:41:08.109]         }
[17:41:08.109]       ]
[17:41:08.109]     }
[17:41:08.109]   ]
[17:41:08.109] }
[17:41:08.109] Error: Server responded with status code 403, Forbidden. Please check that your client ID, URL and read only token are configured properly.
[17:41:08.109] 
[17:41:08.109] Message from server: invalid credentials Please see our FAQ for more information: https://tina.io/docs/errors/faq/
[17:41:08.110]     at request (/vercel/path0/node_modules/@tinacms/cli/dist/index.js:2314:11)
[17:41:08.110]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[17:41:08.110]     at async BuildCommand.checkClientInfo (/vercel/path0/node_modules/@tinacms/cli/dist/index.js:2168:19)
[17:41:08.110]     at async BuildCommand.execute (/vercel/path0/node_modules/@tinacms/cli/dist/index.js:2116:7)
[17:41:08.110]     at async BuildCommand.validateAndExecute (/vercel/path0/node_modules/clipanion/lib/advanced/Command.js:73:26)
[17:41:08.110]     at async Cli.run (/vercel/path0/node_modules/clipanion/lib/advanced/Cli.js:223:24)
[17:41:08.110]     at async Cli.runExit (/vercel/path0/node_modules/clipanion/lib/advanced/Cli.js:232:28)
[17:41:08.134] error Command failed with exit code 1.
[17:41:08.135] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[17:41:08.162] Error: Command "yarn run build" exited with 1
[17:41:08.928] Deployment completed
[17:41:08.543] BUILD_UTILS_SPAWN_1: Command "yarn run build" exited with 1
```

See also:

- [failing deployment (example)](https://vercel.com/startup-nights/website/GnKCSkpfMuCKkutz3cGWw9oWkgTX)
- [tina docs regarding drafts](https://tina.io/docs/drafts/overview/)
- [preview URL - vercel docs](https://vercel.com/docs/concepts/deployments/preview-deployments#preview-urls)

**Comment by joergmis** [comment]
> Please check that your client ID, URL and read only token are configured properly.

Apparently, you need a read-only token. So the configuration is:

- add a glob pattern to the site URL in the tina cloud project config to match the preview deployment url
- set up a read-only token that is used for preview deployments
